### ISSUE TITLE
Connection closed by remote host

### ISSUE THREAD

**Issue by Ahgdaba** [AnimMouse/frp-flyapp#1]

**Comment by bram-dingelstad** [comment]
hey! im using your config files and i am running into this issue as well on Minecraft, what did you do to solve it?

**Comment by AnimMouse** [comment]
@bram-dingelstad Connection closed by remote host probably means that you are connecting to the wrong port, using a wrong protocol for connecting to frps, port mapping on `fly.toml` is wrong, or you are using a shared IP address instead of a dedicated IP address.

**Comment by bram-dingelstad** [comment]
Cool! i’ll go through that list to see if that resolves it!

**Comment by bram-dingelstad** [comment]
Okay, reporting back since I solved it, but for future reference for someone else:


Turns out that Fly will also keep your non static IP up, I still had my domain pointing to that, when i thought i had a CNAME

So, to anyone reading this with the same problem, make sure that you are pointing / using the static IP that you bought rather than the one you've been using to refer to your Fly service up to that point, and you should be fine!
